#!/usr/bin/env python

# Copyright (C) <2015> EMBL-European Bioinformatics Institute

# This program is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation, either version 3 of
# the License, or (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.

# Neither the institution name nor the name screenings can
# be used to endorse or promote products derived from this
# software without prior written permission. For written
# permission, please contact <marco@ebi.ac.uk>.

# Products derived from this software may not be called
# screenings nor may screenings appear in their names
# without prior written permission of the developers.
# You should have received a copy of the GNU General Public
# License along with this program. If not, see
# <http://www.gnu.org/licenses/>.

__author__ = "Marco Galardini"
__version__ = "0.0.1"

def get_options():
    import argparse

    # create the top-level parser
    description = "Indicate the most frequently missing strains"
    parser = argparse.ArgumentParser(description = description,
                                     prog = 'missing_colonies')
    parser.add_argument('idir', action='store',
                        help='Iris files directory'+
                        '(only files ending in *.iris will be loaded)')
    parser.add_argument('platefile', action='store',
                        help='Plate information file')

    parser.add_argument('--size', action='store',
                type=float,
                default=0,
                help='Size threshold: colonies smaller than this will'
                ' be considered [Default: 0]')
    
    parser.add_argument('--percentile', action='store',
                default=0.95,
                type=float,
                help='Percentile threshold for the number of missing colonies'+
                ' per plate, based on the total number of plates [Default: 0.95]')
    
    parser.add_argument('--version', action='version',
                         version='%(prog)s '+__version__)

    return parser.parse_args()

if __name__ == "__main__":
    import sys
    import os
    import screenings as sc

    options = get_options()

    plates = {}
    ps = set()
    missing = {}

    for f in filter(lambda x: x.endswith('.iris'),
            os.listdir(options.idir)):
        strains = {}

        p = f.split('-')[2].split('_')[0]
        ps.add( p )

        plates[p] = plates.get(p, 0)
        plates[p] += 1

        m = sc.parse_iris(os.path.join(options.idir, f),
                options.platefile, platenumber=p)
        for r, c in zip(m[m['colony size'] <= options.size]['row'],
                        m[m['colony size'] <= options.size]['column']):
            missing[(p, r, c)] = missing.get((p, r, c), 0)
            missing[(p, r, c)] += 1

            # Check whether all the replicates of this strain are
            # consistently missing
            strain = m[(m.row == r) &
                   (m.column == c)].index[0]
            strains[(p, strain)] = strains.get((p, strain), 0)
            strains[(p, strain)] += 1
    
        # If all the replicates are missing, it is most probably a biological
        # phenomenon, so reduce the count for this strain
        for strain in filter(lambda x: strains[x] == m.loc[x[1]].shape[0],
                             strains):
            for r, c in zip(m.loc[strain[1], 'row'],
                               m.loc[strain[1], 'column']):
                missing[(strain[0], r, c)] -= 1
        
    # Fill all the dict
    for p, r, c in zip(ps, 
                    m['row'],
                    m['column']):
        missing[(p, r, c)] = missing.get((p, r, c), 0)

    for p, v in plates.items():
        threshold = v * options.percentile

        sys.stderr.write('Picking a missing threshold of %d plates for %s'%(threshold, p))
        sys.stderr.write('\n')

        for plate, r, c in filter(lambda x: missing[x] > threshold,
                missing):
            if plate == p:
                print('%s\t%d\t%d'%(p, r, c))
